# Generated by Django 5.1.3 on 2024-11-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productlistApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_list',
            old_name='Passworld1',
            new_name='Password1',
        ),
        migrations.RenameField(
            model_name='user_list',
            old_name='Passworld2',
            new_name='Password2',
        ),
    ]
