# Generated by Django 5.1.3 on 2024-11-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlistApp', '0002_rename_passworld1_user_list_password1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_item_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Price', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('Images', models.ImageField(upload_to='products_imges')),
            ],
        ),
    ]
