# Generated by Django 5.1.3 on 2024-11-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlistApp', '0003_product_item_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_item_list',
            name='Rate',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
