# Generated by Django 5.1.3 on 2024-11-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlistApp', '0005_user_list_is_admin_alter_product_item_list_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_to_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Userid', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=255)),
                ('Product_obj', models.CharField(max_length=255)),
            ],
        ),
    ]
