# Generated by Django 5.1.3 on 2024-11-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlistApp', '0008_alter_add_to_cart_list_product_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart_list',
            name='Product_obj',
            field=models.JSONField(),
        ),
    ]
