# Generated by Django 5.1.3 on 2024-11-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlistApp', '0009_alter_add_to_cart_list_product_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart_list',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='add_to_cart_list',
            name='TotalPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
