# Generated by Django 5.1.3 on 2024-11-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlistApp', '0010_add_to_cart_list_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_item_list',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
